# fly.toml app configuration file generated for notes-app-master on 2024-11-06T23:28:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-app-master'
primary_region = 'fra'

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = 'Value goes here'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
